// chapter 8/cross-framework-counter/Counter.jsx
// React 19 (function component)
import { useState, useMemo } from 'react'

export default function Counter() {
  const [n, setN] = useState(0)
  const isEven = useMemo(() => n % 2 === 0, [n])
  return (
    <>
      <button onClick={() => setN(n + 1)}>+1</button>
      <p>{n} ({isEven ? 'even' : 'odd'})</p>
    </>
  )
}

// chapter 8/cross-framework-counter/counter.component.ts
// Angular 17+ (signals)
import { Component, computed, signal } from '@angular/core'

@Component({
  selector: 'app-counter',
  standalone: true,
  template: `
    <button (click)="n.set(n() + 1)">+1</button>
    <p>{{ n() }} ({{ isEven() ? 'even' : 'odd' }})</p>
  `,
})
export class Counter {
  n = signal(0)
  isEven = computed(() => this.n() % 2 === 0)
}
